
GET http://localhost:3001/allItems/asc

####

GET http://localhost:3001/allItems


###

POST http://localhost:3001/additem

Content-Type: application/json

{
	"itemId": 107,
	"itemName": "Check",
	"itemCost": 21.22
}

####

GET http://localhost:3001/item/77
