
GET http://localhost:3001/allItems/asc

####

GET http://localhost:3001/allItems


###

POST http://localhost:3001/additem

Content-Type: application/json
{
    "itemNo": 177,
    "itemName": "Test Update1",
    "itemPrice": 2.25
}

####

GET http://localhost:3001/item/77
